apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  template:
    metadata:
      labels: 
        name: aplicacao-pod
    spec:
      containers:
        - name: container-aplicacao
          image: vanderzago/moneyapi:1.1.0
          ports:
            - containerPort: 8080